apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-matrix
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/santosh-gh/k8s-18-deployment.git
          revision: HEAD
          directories:
          - path: multi-manifests/*
      - list:
          elements:
          - namespace: dev
          - namespace: test
          - namespace: prod
  template:
    metadata:
      name: '{{path.basename}}-{{namespace}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/santosh-gh/k8s-18-deployment.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: test-namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
