apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-env-multi-manifests
spec:
  generators:
    - matrix:
        generators:
          # List of microservices
          - list:
              elements:
                - name: config                 
                - name: rabbitmq                  
                - name: order                
                - name: product                
                - name: store-front                    

          # List of environments
          - list:
              elements:
                - namespace: dev
                - namespace: test
                - namespace: prod
  template:
    metadata:
      name: '{{name}}-{{namespace}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/santosh-gh/k8s-18-deployment.git
        targetRevision: HEAD
        # Each service can have overlays for each env
        path: 'multi-manifests/{{name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true